### ISSUE TITLE
Generated annotation file for custom dataset

### ISSUE THREAD

**Issue by Dipankar1997161** [david8862/tf-keras-stacked-hourglass-keypoint-detection#11]
Hey!
I have successfully generated the annotation file for my custom dataset, however, I require a small clarification.
When I opened the annotation file, upon checking the first few lines, "image paths" included the path of images of the validation dataset. 
Is this natural for such an annotation file? or is there any error? 

Looking forward to your response.

**Comment by david8862** [comment]
@Dipankar1997161 you can check `isValidation` field in annotation to see if it's a validation sample:
<img width="291" alt="企业微信截图_16507277992707" src="https://user-images.githubusercontent.com/25219223/164912706-834ff6e8-3136-497b-ba81-5f81769d28be.png">
