### ISSUE TITLE
Invalid literal error in Eval.py during training

### ISSUE THREAD

**Issue by Dipankar1997161** [david8862/tf-keras-stacked-hourglass-keypoint-detection#16]
![Screenshot (284)](https://user-images.githubusercontent.com/85514219/165899268-59e2f062-7623-4080-8579-131ee30faa80.png)
My image names are under the format 0xxxxxx_img.png

After training the first epoch, I got the following error as it was not able to generate the "image_id"

for example; 0000115_img.png is my first image and its image_id is 115.

could you provide any input into this. 
I really need help.

@david8862  Hope you reply.

**Comment by david8862** [comment]
by default the MPII/COCO image name are both number string, like `0000115.jpg`. If you use different type, may need to change related code.

**Comment by Dipankar1997161** [comment]
yes, I changed the related code. Basically, the portion where it was getting the basename. 
previously it was "image_id = int(os.path.basename(image_name).split('.')[0])"

For my dataset, its now image_id = int(os.path.basename(image_name).split('_img.')[0])

this resolved the issue.
Thanks for this
