### ISSUE TITLE
Pre-trained model release for MPII dataset

### ISSUE THREAD

**Issue by aitikgupta** [david8862/tf-keras-stacked-hourglass-keypoint-detection#2]
Hey @david8862, awesome work!
I see some of the pretrained models you [released](https://github.com/david8862/tf-keras-stacked-hourglass-keypoint-detection/releases/tag/v1.0.0), they only contain  the models trained on COCO dataset.
Could I request you to release the same models trained on MPII dataset (along with their PCKh values)?
Thankyou :D

**Comment by david8862** [comment]
@aitikgupta the original repo [Stacked_Hourglass_Network_Keras](https://github.com/yuanyuanli85/Stacked_Hourglass_Network_Keras) has provided some MPII pretrained models, so I didn't go through this part. Maybe you can get from there and it should be also available for this repo.

**Comment by aitikgupta** [comment]
Indeed, thanks 👍🏼
