### ISSUE TITLE
FileNotFound [Errno2]

### ISSUE THREAD

**Issue by Dipankar1997161** [david8862/tf-keras-stacked-hourglass-keypoint-detection#9]
As I was training with the MSCOCO(2014 ) dataset. It suddenly throws an error of FileNotFound for an image numer 000000196842.jpg in the train 2014 folder. 

However, the following image is present as I checked it with "os.path.exists" which gave me "True" as output. 

So am confused, if the file is corrupted or what could be possibly wrong? 
Or should I use 2017 dataset or anything? 

Any help is appreciated!

**Comment by david8862** [comment]
@Dipankar1997161 not sure about your env details. Could you provide the full error log?

**Comment by Dipankar1997161** [comment]
@david8862 here is the snap of the error. Libraries are installed as per the requirements.txt file.
![filenotfound error](https://user-images.githubusercontent.com/85514219/163730572-f7cac6ad-d3ea-41ee-be45-17d7a5b94b50.png)

I tried to redownload the mscoco2017 file and while unzipping, it prompted" do you want to replace "..... jpg". and I entered yes. The jpg file was the same as shown in the error. Is that probably the reason ???? let me know
